version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    build:
      context: .\ProductCatalogAPI
      dockerfile: Dockerfile
    image: jewels/catalogapi
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: catalogDb
      DatabaseUser: sa
      DatabaseUserPassword: ProductApi(!)
      ExternalCatalogBaseUrl: http://localhost:5080
    ports:
      - "5080:80"
    container_name: catalogapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver
  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: jewels/tokenapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:5220
    ports:
      - "5030:80"
    container_name: tokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  webmvc:
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    image: jewels/webmvc
    container_name: webshop
    environment:
      CatalogUrl: http://catalog
      IdentityUrl: http://10.0.75.1:5030      
      CallBackUrl: http://localhost:5220
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5220:80"
    networks:
      - frontend
    depends_on:
      - catalog
      -tokenserver
      
  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    container_name: catalogdb
    ports:
      - "1449:1433"
    networks:
      - backend
